version: '3.7'

volumes:
  zk-data:
  zk-logs:  
  broker-logs:

networks:
  default:
    external:
      name: ${NETWORK}

services:

  zookeeper:
    image: confluentinc/cp-zookeeper:5.1.0    
    container_name: zookeeper
    hostname: zookeeper
    environment:
      ZOOKEEPER_CLIENT_PORT: ${ZOOKEEPER_PORT}
    ports:
      - ${ZOOKEEPER_PORT}:${ZOOKEEPER_PORT}
    volumes:
      - zk-data:/var/lib/zookeeper/data
      - zk-logs:/var/lib/zookeeper/log    

  broker:
    image: confluentinc/cp-kafka:5.1.0    
    container_name: broker
    hostname: broker
    depends_on:
      - zookeeper
    ports:
      - 9092:9092  
      - 19092:19092    
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:${ZOOKEEPER_PORT}
      KAFKA_ADVERTISED_LISTENERS: ${BROKER_ADV_LISTENERS}
      KAFKA_INTER_BROKER_LISTENER_NAME: INTERNAL
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: ${PROTOCOL_MAP}
      KAFKA_LOG_RETENTION_HOURS: ${BROKER_LOG_RETENTION_IN_HOURS}
      KAFKA_LOG_ROLL_HOURS: ${BROKER_LOG_ROLL_IN_HOURS}
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
    volumes:
      - broker-logs:/var/lib/kafka/data
      - ${AWS_SECRETS}:/root/.aws      
  
  connect1:
    image: confluentinc/cp-kafka-connect:5.2.1
    container_name: connect1
    hostname: connect1
    depends_on:
      - zookeeper
      - broker
    ports:
      - 18083:18083
    environment:
      CONNECT_BOOTSTRAP_SERVERS: broker:9092
      CONNECT_REST_PORT: 18083
      CONNECT_GROUP_ID: "s3-sink"
      CONNECT_CONFIG_STORAGE_TOPIC: "__s3-sink-config"
      CONNECT_OFFSET_STORAGE_TOPIC: "__s3-sink-offsets"
      CONNECT_STATUS_STORAGE_TOPIC: "__s3-sink-status"
      CONNECT_CONFIG_STORAGE_REPLICATION_FACTOR: 1
      CONNECT_OFFSET_STORAGE_REPLICATION_FACTOR: 1
      CONNECT_STATUS_STORAGE_REPLICATION_FACTOR: 1      
      CONNECT_KEY_CONVERTER: "org.apache.kafka.connect.storage.StringConverter"
      CONNECT_VALUE_CONVERTER: "org.apache.kafka.connect.json.JsonConverter"
      CONNECT_INTERNAL_KEY_CONVERTER: "org.apache.kafka.connect.json.JsonConverter"
      CONNECT_INTERNAL_VALUE_CONVERTER: "org.apache.kafka.connect.json.JsonConverter"
      CONNECT_REST_ADVERTISED_HOST_NAME: "connect1"
      CONNECT_PLUGIN_PATH: /usr/share/java 
      CONNECT_SCHEMAS_ENABLE: "false"
      CONNECT_VALUE_CONVERTER_SCHEMAS_ENABLE: "false"
      CONNECT_KEY_CONVERTER_SCHEMAS_ENABLE: "false"            
    volumes:
      - ${AWS_SECRETS}:/root/.aws

  connect2:
    image: confluentinc/cp-kafka-connect:5.2.1
    container_name: connect2
    hostname: connect2
    depends_on:
      - zookeeper
      - broker
    ports:
      - 28083:28083
    environment:
      CONNECT_BOOTSTRAP_SERVERS: broker:9092
      CONNECT_REST_PORT: 28083
      CONNECT_GROUP_ID: "s3-sink"
      CONNECT_CONFIG_STORAGE_TOPIC: "__s3-sink-config"
      CONNECT_OFFSET_STORAGE_TOPIC: "__s3-sink-offsets"
      CONNECT_STATUS_STORAGE_TOPIC: "__s3-sink-status"
      CONNECT_CONFIG_STORAGE_REPLICATION_FACTOR: 1
      CONNECT_OFFSET_STORAGE_REPLICATION_FACTOR: 1
      CONNECT_STATUS_STORAGE_REPLICATION_FACTOR: 1      
      CONNECT_KEY_CONVERTER: "org.apache.kafka.connect.storage.StringConverter"
      CONNECT_VALUE_CONVERTER: "org.apache.kafka.connect.json.JsonConverter"
      CONNECT_INTERNAL_KEY_CONVERTER: "org.apache.kafka.connect.json.JsonConverter"
      CONNECT_INTERNAL_VALUE_CONVERTER: "org.apache.kafka.connect.json.JsonConverter"
      CONNECT_REST_ADVERTISED_HOST_NAME: "connect2"
      CONNECT_PLUGIN_PATH: /usr/share/java 
      CONNECT_SCHEMAS_ENABLE: "false"
      CONNECT_VALUE_CONVERTER_SCHEMAS_ENABLE: "false"
      CONNECT_KEY_CONVERTER_SCHEMAS_ENABLE: "false"            
    volumes:
      - ${AWS_SECRETS}:/root/.aws  

  # schema-registry:
  #   image: confluentinc/cp-schema-registry:5.1.0
  #   container_name: schema-registry
  #   hostname: schema-registry
  #   restart: always
  #   depends_on:
  #     - zookeeper
  #     - broker
  #   ports:
  #     - "18081:8081"
  #   environment:
  #     SCHEMA_REGISTRY_HOST_NAME: schema-registry
  #     SCHEMA_REGISTRY_LISTENERS: "http://0.0.0.0:18081"
  #     SCHEMA_REGISTRY_KAFKASTORE_BOOTSTRAP_SERVERS: PLAINTEXT://broker:19092

  # ksql-server:
  #   image: "confluentinc/cp-ksql-server:5.1.0"
  #   container_name: ksql-server
  #   hostname: ksql-server
  #   depends_on:
  #     - broker
  #     - schema-registry
  #   ports:
  #     - "8088:8088"
  #   environment:
  #     KSQL_HOST_NAME: ksql-server
  #     KSQL_BOOTSTRAP_SERVERS: broker:9092
  #     KSQL_LISTENERS: http://0.0.0.0:8088
  #     KSQL_KSQL_SCHEMA_REGISTRY_URL: http://schema-registry:18081

  # ksql-cli:
  #   image: confluentinc/cp-ksql-cli:5.1.0
  #   container_name: ksql-cli
  #   depends_on:
  #     - broker
  #     - ksql-server
  #   entrypoint: /bin/sh
  #   tty: true